<a href="https://colab.research.google.com/github/Abimbola-ai/Blood-Spectorscopy/blob/main/data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Research Links:
* https://www.researchgate.net/publication/258716133_Miniature_Near-Infrared_NIR_Spectrometer_Engine_For_Handheld_Applications

* https://journals.sagepub.com/doi/abs/10.1255/jnirs.1084

In [4]:
!pip install -q efficientnet

In [5]:
import pandas as pd
import ssl
from sklearn.cluster import KMeans
import numpy as np
import json
import random, string
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm
# import sweetviz as sv
tqdm.pandas()
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split,cross_val_score, StratifiedKFold, StratifiedShuffleSplit, GroupKFold
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_recall_curve, f1_score, roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
# from lightgbm import LGBMClassifier
# import lightgbm as lgb
# from xgboost import XGBClassifier
# from catboost import CatBoostClassifier
import tensorflow as tf
import tensorflow.keras.layers as L

import efficientnet.tfkeras as efn
%matplotlib inline
sns.set_style("whitegrid")
seed = 42

ssl._create_default_https_context = ssl._create_unverified_context
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


In [6]:
# Import the dataset
train = pd.read_csv('Updated_Train.csv', index_col=0)
test = pd.read_csv('Updated_Test.csv', index_col=0)
# train_trimmed = pd.read_csv('Data/Updated_Train_trimmed.csv', index_col=0)
# test_trimmed = pd.read_csv("Data/Updated_Test_trimmed.csv", index_col=0)
spectra_hgb = pd.read_csv('Spectra_hgb.csv', index_col=0).reset_index()
spectra_chol = pd.read_csv('Spectra_chl.csv', index_col=0)
spectra_glu = pd.read_csv('Spectra_gluc.csv', index_col=0).reset_index()
spectra_skinfatblood = pd.read_csv('Spectra_skinfatblood.csv', index_col=0)


### **Exploratory Data Analysis**

In [7]:
train.head()

absorbance0  absorbance1  ...  cholesterol_ldl_human  donation_id
0     0.520883     0.528200  ...                   high         2250
1     0.529109     0.534852  ...                   high         2250
2     0.528434     0.532036  ...                   high         2250
3     0.530528     0.531880  ...                   high         2250
4     0.527530     0.536424  ...                   high         2250

[5 rows x 178 columns]

In [8]:
test.head()

Reading_ID donation_id  absorbance0  ...     std  temperature  humidity
0  ID_KWUAQLRM     ID_2982     0.517951  ...  0.0027        37.09     27.22
1  ID_FN8SIVJJ     ID_2982     0.517839  ...  0.0027        37.20     27.17
2  ID_CI4TQCHI     ID_2982     0.517702  ...  0.0027        37.30     27.07
3  ID_URJMKNU7     ID_2982     0.525008  ...  0.0027        37.38     26.98
4  ID_HBJH67IS     ID_2982     0.520532  ...  0.0027        37.48     26.89

[5 rows x 176 columns]

Removing donation_id 6824 from the train data as the data producer said it is not good.

In [9]:
dropped_index =  train[train["donation_id"] == 6824].index 
train_df = train.drop(dropped_index)
print(f"Train data shape is:",train_df.shape)
print(f"Test data shape is:",test.shape)

Train data shape is: (29100, 178)
Test data shape is: (3660, 176)


`Reading_ID` is in test but not in train. There are three target columns in the train dataset, `hdl_cholesterol_human`, `hemoglobin(hgb)_human`, and `cholesterol_ldl_human` - Multi target data. 

The data from each samples are repeated about 60 times at different temperatures and humidity which were said to affect the spectrum data. This might cause overfitting if fed into the model. How do I segment this data? 

In [10]:
print(f"There are",train_df["donation_id"].nunique(), "donation ids in the dataset")

There are 485 donation ids in the dataset


In [11]:
train_df.describe()

absorbance0   absorbance1  ...      humidity  donation_id
count  29100.000000  29100.000000  ...  29100.000000  29100.00000
mean       0.508006      0.510224  ...     35.342783   6647.34433
std        0.039435      0.039200  ...      8.709672   3039.12087
min        0.237409      0.251987  ...     16.610000   1975.00000
25%        0.486414      0.488268  ...     28.270000   3593.00000
50%        0.509504      0.511795  ...     35.310000   6427.00000
75%        0.530544      0.532483  ...     41.200000   9326.00000
max        0.657782      0.652291  ...     67.820000  11906.00000

[8 rows x 175 columns]

There seems to be no outlier in the dataset. 

In [12]:
# Check the unique values of the targets
print(train_df["hdl_cholesterol_human"].unique())
print(train_df["hemoglobin(hgb)_human"].unique())
print(train_df["cholesterol_ldl_human"].unique())

['low' 'ok' 'high']
['ok' 'low' 'high']
['high' 'ok' 'low']


This looks uniform, all target variables are classified into `low`, `ok` and `high`.

In [13]:
# Check for missing value
print(str(train_df.isnull().sum().sum()) + " missing value in train")
print(str(test.isnull().sum().sum()) + " missing value in test")

0 missing value in train
0 missing value in test


In [14]:
#Labelencode the targets
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train_df["hdl_cholesterol_human"] = le.fit_transform(train_df["hdl_cholesterol_human"])
train_df["hemoglobin(hgb)_human"]= le.fit_transform(train_df["hemoglobin(hgb)_human"])
train_df["cholesterol_ldl_human"]= le.fit_transform(train_df["cholesterol_ldl_human"])

### Splitting the dataset into GroupKfold

In [15]:
group_by_donation_id = train_df.groupby(['donation_id','id']) 
group_by_donation_id.first()

absorbance0  ...  cholesterol_ldl_human
donation_id id                  ...                       
1975        12120     0.511340  ...                      2
            12121     0.502340  ...                      2
            12122     0.507582  ...                      2
            12123     0.508379  ...                      2
            12124     0.507252  ...                      2
...                        ...  ...                    ...
11906       20055     0.543958  ...                      0
            20056     0.535434  ...                      0
            20057     0.528145  ...                      0
            20058     0.533171  ...                      0
            20059     0.546692  ...                      0

[29100 rows x 176 columns]

It clearly shoes that one donor can have multiple `id`. We will do the splitting below.

# Convert the target 

In [16]:
groups_by_donation_id_list = train_df['donation_id'].copy().tolist()
y_labels = train_df[["hdl_cholesterol_human","hemoglobin(hgb)_human","cholesterol_ldl_human"]].values
y_labels

array([[1, 2, 0],
       [1, 2, 0],
       [1, 2, 0],
       ...,
       [1, 2, 0],
       [1, 2, 0],
       [1, 2, 0]])

Creating 5 folds and appended the grouped dataframes into a list. 

In [17]:
n_splits = 5
gkf = GroupKFold(n_splits = 5)

result = []   
for train_idx, val_idx in gkf.split(train_df, y_labels, groups = groups_by_donation_id_list):
    train_fold = train_df.iloc[train_idx]
    val_fold = train_df.iloc[val_idx]
    result.append((train_fold, val_fold))

train_fold_1, val_fold_1 = result[0][0],result[0][1]
train_fold_2, val_fold_2 = result[1][0],result[1][1]
train_fold_3, val_fold_3 = result[2][0],result[2][1]
train_fold_4, val_fold_4 = result[3][0],result[3][1]
train_fold_5, val_fold_5 = result[4][0],result[4][1]

# just to check if it works as intended
# sample = train_fold_1.groupby("donation_id")
# sample.get_group(2250)
# sample.get_group(2250).count()


##Baseline Modeling - Logistic Regression

In [18]:
from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix, roc_auc_score ,roc_curve,auc
from sklearn.model_selection import GridSearchCV,StratifiedKFold

### Fold 1

In [19]:
train_fold_1

absorbance0  absorbance1  ...  cholesterol_ldl_human  donation_id
0         0.520883     0.528200  ...                      0         2250
1         0.529109     0.534852  ...                      0         2250
2         0.528434     0.532036  ...                      0         2250
3         0.530528     0.531880  ...                      0         2250
4         0.527530     0.536424  ...                      0         2250
...            ...          ...  ...                    ...          ...
29155     0.506799     0.509514  ...                      0         1994
29156     0.510311     0.506805  ...                      0         1994
29157     0.511655     0.513587  ...                      0         1994
29158     0.512617     0.514809  ...                      0         1994
29159     0.523990     0.522537  ...                      0         1994

[23280 rows x 178 columns]

In [20]:
from sklearn.preprocessing import StandardScaler
def scaler(df):
  scale = StandardScaler()
  df_scaled = scale.fit_transform(df)
  return df_scaled


In [21]:
train_fold_1.drop(["id"], axis=1, inplace=True)
val_fold_1.drop(["id"], axis=1, inplace=True)

train_1 = train_fold_1.to_numpy()
val_1 = val_fold_1.to_numpy()
features_tr = np.array(train_1[:,:173], dtype=float)
features_val = np.array(val_1[:,:173], dtype=float)
scaler(features_tr)
scaler(features_val)
labels_tr = train_1[:, 173:176]
labels_val = val_1[:, 173:176]

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


array([[ 0.31899139,  0.44945583,  0.39399203, ..., -1.06080539,
        -0.72027595,  1.05392456],
       [ 0.52385703,  0.61639937,  0.67748412, ..., -1.06080539,
        -0.67716646,  1.04464705],
       [ 0.50703238,  0.54573661,  0.66082863, ..., -1.06080539,
        -0.63764942,  1.03420985],
       ...,
       [ 0.0891952 ,  0.08271442,  0.1200951 , ...,  0.5139148 ,
         1.54656507,  0.22358697],
       [ 0.113157  ,  0.11339187,  0.13259584, ...,  0.5139148 ,
         1.55374998,  0.21894821],
       [ 0.39637775,  0.30733067,  0.26270526, ...,  0.5139148 ,
         1.55734244,  0.2201079 ]])

array([[ 0.49373258,  0.67343231,  0.48177004, ..., -0.93868479,
        -0.44335735, -0.36178351],
       [ 0.48464661,  0.54519652,  0.39029912, ..., -0.93868479,
        -0.41027645, -0.37738784],
       [ 0.71048734,  0.631831  ,  0.62341256, ..., -0.93868479,
        -0.38711983, -0.39856514],
       ...,
       [-1.13019153, -1.1196593 , -1.16581687, ...,  0.50790389,
         1.41909719,  0.20220149],
       [-1.15277667, -1.19297486, -1.14016673, ...,  0.50790389,
         1.43232955,  0.20220149],
       [-1.36861557, -1.30715974, -1.28182838, ...,  0.50790389,
         1.43894573,  0.20220149]])

In [22]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(class_weight='balanced', random_state=42)
multi_target_lr = MultiOutputClassifier(logreg, n_jobs=-1)
multi_target_lr.fit(features_tr,labels_tr)
multi_target_lr.score(features_val,labels_val)

MultiOutputClassifier(estimator=LogisticRegression(class_weight='balanced',
                                                   random_state=42),
                      n_jobs=-1)

0.04398625429553265

In [23]:
params = {'penalty':['l1', 'l2', 'elasticnet'], 'C':[10**i for i in range(-4,5)], 'solver':['liblinear','sag']}
log_model = LogisticRegression(random_state=42, class_weight='balanced')
# log_clf = hyperparameter_model(log_model, params, df_train_scaled, y_train)
# print(log_clf.best_params_)

In [29]:
from sklearn.utils._testing import ignore_warnings
from sklearn.exceptions import ConvergenceWarning
# with warnings.catch_warnings():
#     warnings.filterwarnings("ignore", category=ConvergenceWarning)

In [ ]:
logreg = LogisticRegression(class_weight='balanced', random_state=42)

# param = {'C':[0.001,0.003,0.005,0.01,0.03,0.05,0.1,0.3,0.5,1,2,3,3,4,5,10,20]}
grid_clf= GridSearchCV(log_model,param_grid=params,scoring='accuracy',refit=True,cv=10)
multi_target_lr = MultiOutputClassifier(grid_clf)
multi_target_lr.fit(features_tr,labels_tr)
# multi_target_lr.score(features_val,labels_val)
print('Best roc_auc: {:.4}, with best C: {}'.format(multi_target_lr.best_score_, multi_target_lr.best_params_))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter